name: Build LuaJIT for Linux

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # Tetap pake 20.04 biar GLIBC kompatibel sama Vercel
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Download LuaJIT Source (Fast Mirror)
      # GANTI KE GITHUB MIRROR BIAR GAK LEMOT
      run: git clone https://github.com/LuaJIT/LuaJIT.git luajit

    - name: Compile LuaJIT
      run: |
        cd luajit
        make CCOPT="-static-libgcc"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: luajit-linux-binary
        path: luajit/src/luajit
