name: Build LuaJIT for Linux

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
<<<<<<< HEAD
    # GANTI INI: Pake ubuntu-20.04 biar GLIBC-nya lebih tua (v2.31) dan masuk ke Vercel/AWS
=======
    # Wajib 20.04 biar GLIBC cocok sama Vercel
>>>>>>> 37454f9e9ece74f5ebea038c0c92c0b16c82f3c1
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Download LuaJIT Source (Fast Mirror)
      # Pake mirror Github biar downloadnya instan (gak bakal timeout kayak luajit.org)
      run: git clone --depth 1 https://github.com/LuaJIT/LuaJIT.git luajit

<<<<<<< HEAD
    - name: Compile LuaJIT
      # Tambahin static flag biar lebih aman
      run: |
        cd luajit
        make CCOPT="-static-libgcc"
=======
    - name: Compile LuaJIT (Turbo Mode)
      run: |
        cd luajit
        # -j$(nproc) = Pake semua otak CPU biar ngebut
        make -j$(nproc) CCOPT="-static-libgcc"
>>>>>>> 37454f9e9ece74f5ebea038c0c92c0b16c82f3c1

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: luajit-linux-binary
        path: luajit/src/luajit