name: Build LuaJIT 32-bit (AMALG STATIC)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:20.04

    steps:
    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y git make gcc libc6-dev gcc-multilib

    - uses: actions/checkout@v3

    - name: Download LuaJIT
      run: git clone --depth 1 https://github.com/LuaJIT/LuaJIT.git luajit

    # --- 32-BIT (MODE AMALG + STATIC) ---
    - name: Compile 32-bit (AMALG)
      run: |
        cd luajit
        make clean
        # "amalg" bikin strukturnya beda total (Git pasti detect beda)
        # LDFLAGS="-static" ditaruh di environment variable biar ke-inject paksa
        export LDFLAGS="-static"
        make amalg -j$(nproc) CC="gcc -m32 -static"
        
        # Simpan hasil
        mkdir -p ../output/32/jit
        cp src/luajit ../output/32/
        cp src/jit/*.lua ../output/32/jit/

    # --- 64-BIT (Standard Static) ---
    - name: Compile 64-bit
      run: |
        cd luajit
        make clean
        make -j$(nproc) CC="gcc -static"
        
        mkdir -p ../output/64/jit
        cp src/luajit ../output/64/
        cp src/jit/*.lua ../output/64/jit/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: luajit-final-bundle
        path: output/
