name: Build LuaJIT for Linux

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # WAJIB: Pake 20.04 biar GLIBC cocok sama Vercel (Jangan ganti latest!)
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    # Pake mirror GitHub biar download cepet & gak timeout
    - name: Download LuaJIT Source
      run: git clone --depth 1 https://github.com/LuaJIT/LuaJIT.git luajit

    # Compile pake mode ngebut (multicore) + static link
    - name: Compile LuaJIT
      run: |
        cd luajit
        make -j$(nproc) CCOPT="-static-libgcc"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: luajit-linux-binary
        path: luajit/src/luajit