name: Build LuaJIT for Linux

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # GANTI INI: Pake ubuntu-20.04 biar GLIBC-nya lebih tua (v2.31) dan masuk ke Vercel/AWS
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Download LuaJIT Source
      run: git clone https://luajit.org/git/luajit.git

    - name: Compile LuaJIT
      # Tambahin static flag biar lebih aman
      run: |
        cd luajit
        make CCOPT="-static-libgcc"

    - name: Upload Artifact (Hasil)
      uses: actions/upload-artifact@v4
      with:
        name: luajit-linux-binary
        path: luajit/src/luajit
