name: Build LuaJIT for Linux

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # Kita pake mesin paling baru biar antrian ngebut...
    runs-on: ubuntu-latest
    
    # ...TAPI kita jalanin prosesnya di dalem "Kapsul Waktu" Ubuntu 20.04
    # Ini kuncinya biar GLIBC-nya tetep versi jadul (Kompatibel Vercel)
    container: 
      image: ubuntu:20.04

    steps:
    - name: Install System Dependencies (Karena container kosongan)
      run: |
        apt-get update
        apt-get install -y git make gcc libc6-dev

    - uses: actions/checkout@v3

    - name: Download LuaJIT (Mirror GitHub)
      run: git clone --depth 1 https://github.com/LuaJIT/LuaJIT.git luajit

    - name: Compile LuaJIT (Turbo Mode)
      run: |
        cd luajit
        make -j$(nproc) CCOPT="-static-libgcc"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: luajit-linux-binary
        path: luajit/src/luajit
        
