name: Build LuaJIT for Linux

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # Wajib 20.04 biar GLIBC cocok sama Vercel
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Download LuaJIT Source (Fast Mirror)
      # Pake mirror Github biar downloadnya instan (gak bakal timeout kayak luajit.org)
      run: git clone --depth 1 https://github.com/LuaJIT/LuaJIT.git luajit

    - name: Compile LuaJIT (Turbo Mode)
      run: |
        cd luajit
        # -j$(nproc) = Pake semua otak CPU biar ngebut
        make -j$(nproc) CCOPT="-static-libgcc"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: luajit-linux-binary
        path: luajit/src/luajit
