name: Build LuaJIT Dual Arch + QEMU (Vercel Fix)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:20.04

    steps:
    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y git make gcc libc6-dev gcc-multilib wget

    - uses: actions/checkout@v3

    - name: Download LuaJIT
      run: git clone --depth 1 https://github.com/LuaJIT/LuaJIT.git luajit

    # --- 1. SIAPKAN QEMU (Translator 32-bit) ---
    - name: Download QEMU Static
      run: |
        mkdir -p ../output/32
        # Download Emulator QEMU versi Static (Bisa jalan di mana aja)
        wget https://github.com/multiarch/qemu-user-static/releases/download/v7.2.0-1/qemu-i386-static
        chmod +x qemu-i386-static
        cp qemu-i386-static ../output/32/

    # --- 2. COMPILE 32-BIT (AMALG STATIC) ---
    - name: Compile 32-bit
      run: |
        cd luajit
        make clean
        make amalg -j$(nproc) CC="gcc -m32" TARGET_LDFLAGS="-static -pthread"
        
        mkdir -p ../output/32/jit
        cp src/luajit ../output/32/
        cp src/jit/*.lua ../output/32/jit/

    # --- 3. COMPILE 64-BIT (AMALG STATIC) ---
    - name: Compile 64-bit
      run: |
        cd luajit
        make clean
        make amalg -j$(nproc) CC="gcc" TARGET_LDFLAGS="-static -pthread"
        
        mkdir -p ../output/64/jit
        cp src/luajit ../output/64/
        cp src/jit/*.lua ../output/64/jit/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: luajit-final-bundle
        path: output/
