name: Build LuaJIT for Linux

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:20.04  # Tetap pake trik container 20.04

    steps:
    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y git make gcc libc6-dev

    - uses: actions/checkout@v3

    - name: Download LuaJIT
      run: git clone --depth 1 https://github.com/LuaJIT/LuaJIT.git luajit

    - name: Compile
      run: |
        cd luajit
        make -j$(nproc) CCOPT="-static-libgcc"

    - name: Prepare Artifact
      run: |
        mkdir -p output/bin/jit
        cp luajit/src/luajit output/bin/
        cp luajit/src/jit/*.lua output/bin/jit/

    - name: Upload Artifact (Binary + Library)
      uses: actions/upload-artifact@v4
      with:
        name: luajit-complete-bundle
        path: output/
